name: Spark Connector Integration Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: sbt integtation test
    runs-on: ubuntu-latest
    strategy:
     matrix:
       scala_version: [ '2.12.8', '2.11.12' ]
       spark_version: [ '2.4.0' ]
       use_copy_unload: [ 'false', 'true' ]
       cloud_provider: [ 'aws', 'gcp' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decrypt snowflake.json for testing
      run: ./.github/scripts/decrypt_secret.sh
      env:
        SNOWFLAKE_TEST_PROFILE_SECRET: ${{ secrets.SNOWFLAKE_TEST_PROFILE_SECRET }}
    - name: Run tests
      run: ./.github/scripts/run-tests-github.sh
      env:
        INTEGRATION_TESTS: true
        SPARK_SCALA_VERSION: ${{ matrix.scala_version }}
        SPARK_VERSION: ${{ matrix.spark_version }}
        SNOWFLAKE_TEST_ACCOUNT: ${{ matrix.cloud_provider }}
        SPARK_CONN_ENV_USE_COPY_UNLOAD: ${{ matrix.use_copy_unload }}
    - name: Update test coverage report
      run: bash <(curl -s https://codecov.io/bash)
